services:
  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pasien_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - ./backend:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    expose:
      - 9000
    environment:
      - DB_HOST=db
      - DB_DATABASE=pasien_db
      - DB_USERNAME=user
      - DB_PASSWORD=password
    command: ["/bin/sh", "-c", "php artisan migrate --force && php-fpm"]
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:9000 || exit 1"]
    #   interval: 10s
    #   retries: 10
    #   timeout: 5s
    #   start_period: 20s

  nginx:
    image: nginx:1.26.3
    ports:
      - "9000:80"
    volumes:
      - ./backend:/var/www/html
      - ./backend/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      # backend:
      #   condition: service_healthy
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - nginx
      # nginx:
      #   condition: service_healthy
    networks:
      - app-network
    environment:
      - VITE_BASE_API_URL="http://nginx:80"

networks:
  app-network:
    driver: bridge
